### ISSUE TITLE
Cannot install and cannot compile/run from source

### ISSUE THREAD

**Issue by PQCraft** [Cybolic/vineyard#15]
attempting to install gives:
```
Cannot add PPA: ''This PPA does not support focal''.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package vineyard
```
and running `./vineyard-preferences` after cloning gives
```
gtkcrashhandler could not load GTK 2.0
Traceback (most recent call last):
  File "./vineyard-preferences", line 26, in <module>
    import vineyard
  File "/home/pqcraft/Downloads/vineyard/vineyard/__init__.py", line 9, in <module>
    from common import *
  File "/home/pqcraft/Downloads/vineyard/vineyard/common.py", line 7, in <module>
    import glib, gobject, gtk, pango, cairo, re
ImportError: No module named gtk
```

**Comment by Cybolic** [comment]
Thanks for the report. The PPA hasn't been updated in a while, so until I get around to doing that, running from source is probably your best bet.

Which distribution are you running and do you have pygtk 2 installed?

**Comment by PQCraft** [comment]
@Cybolic I installed python-gtk (with some magic as it also is unavailable for focal) and running from source works now
