### ISSUE TITLE
Exception due to 'staging' in version string

### ISSUE THREAD

**Issue by hollunder** [Cybolic/vineyard#5]
$ vineyard-preferences 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/bin/vineyard-preferences", line 500, in get_settings
    self.settings['offrender'] = wine.graphics.getOffscreenRenderingMode()
  File "/usr/lib/python2.7/site-packages/wine/_graphics.py", line 143, in getOffscreenRenderingMode
    if int(self.VERSION.replace('.','')) >= 1123:
ValueError: invalid literal for int() with base 10: '215 (Staging)'

I'm using Arch Linux and the wine-staging package version 2.15. Should be a trivial fix.

**Comment by Cybolic** [comment]
Thanks for the report! Could you tell me what the output of `wine --version` is?
Also, which version of Vineyard are you running?

**Comment by hollunder** [comment]
$ wine --version
wine-2.21 (Staging)

It's gone now, maybe I used this outdated version, I don't recall.
https://aur.archlinux.org/packages/vineyard/
I flagged it out of date now, hope that helps.
I don't know whether you do releases or not.
