### ISSUE TITLE
"Open Terminal in this configuration fails"

### ISSUE THREAD

**Issue by stuaxo** [Cybolic/vineyard#8]
OS - Ubuntu artful 64 bit (17.10), running from git.

```
Traceback (most recent call last):
  File "/home/stu/projects/external/vineyard/vineyard/widgets/tool_open_terminal.py", line 29, in button_clicked
    wine.util.open_terminal(configuration_name=conf_name)
  File "/home/stu/projects/external/vineyard/wine/util.py", line 1302, in open_terminal
    terminal, args = get_default_terminal()
  File "/home/stu/projects/external/vineyard/wine/util.py", line 1260, in get_default_terminal
    terminal = get_command_output('gconftool-2 --get "/desktop/gnome/applications/terminal/exec"')
  File "/home/stu/projects/external/vineyard/wine/util.py", line 793, in get_command_output
    process = run_command(command, stderr, shell, dont_parse_command)
  File "/home/stu/projects/external/vineyard/wine/util.py", line 809, in run_command
    process = common.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/stu/projects/external/vineyard/wine/common.py", line 278, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I don't have gconftool-2 installed, but I wonder if this should be using dconf anyway ?

**Comment by Cybolic** [comment]
Yeah, gconf is outdated these days. I need to add support for dconf and have this as a fallback instead.

**Comment by Cybolic** [comment]
Outside of adding more dependencies (which I'd like to avoid), I haven't been able to find a way to locate the default terminal emulator through dconf or some other standard way, but the latest commit should at least let Vineyard gracefully fall back to either gnome-terminal or xterm.
Could you see if it fixed your issue?

**Comment by stuaxo** [comment]
Cheers, that works :)

I had a look just now and found ```/etc/alternatives/x-terminal-emulator ``` on my system (which seems to be the debian/ubuntu way of storing the default) a symlink to the default terminal emulator

My one was pointing at terminator, which is a pretty ancient terminal emulator, once I uninstalled that it points at gnome-terminal.

**Comment by Cybolic** [comment]
Thanks for the confirmation and the Debian mention. I've added the alternatives symlink as a last fallback; I don't think there's much more I can do here for now :)
